# Generated by Django 3.0.5 on 2020-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Admin',
            fields=[
                ('ad_id', models.AutoField(db_column='ad_id', primary_key=True, serialize=False)),
                ('ad_First_name', models.CharField(max_length=100)),
                ('ad_Lirst_name', models.CharField(max_length=100)),
                ('ad_NIC', models.CharField(max_length=10)),
                ('ad_Email', models.EmailField(max_length=254)),
                ('ad_User_name', models.CharField(max_length=100)),
                ('ad_Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_admin',
            },
        ),
    ]
